#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : funcsigs
Version  : 0.4
Release  : 4
URL      : https://pypi.python.org/packages/source/f/funcsigs/funcsigs-0.4.tar.gz
Source0  : https://pypi.python.org/packages/source/f/funcsigs/funcsigs-0.4.tar.gz
Summary  : Python function signatures from PEP362 for Python 2.6, 2.7 and 3.2+
Group    : Development/Tools
License  : Apache-2.0
Requires: funcsigs-python
BuildRequires : linecache2-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : traceback2-python
BuildRequires : unittest2-python

%description
funcsigs
========
``funcsigs`` is a backport of the `PEP 362`_ function signature features from
Python 3.3's `inspect`_ module. The backport is compatible with Python 2.6, 2.7
as well as 3.2 and up.

%package python
Summary: python components for the funcsigs package.
Group: Default

%description python
python components for the funcsigs package.


%prep
%setup -q -n funcsigs-0.4

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 setup.py test
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
